import type { ComponentType } from "react";

import {
  AlertActionDemo,
  AlertDemo,
  AlertStatusDemo,
} from "~/components/demos/alert";
import {
  AlertDialogDangerDemo,
  AlertDialogDemo,
  AlertDialogSizeDemo,
} from "~/components/demos/alert-dialog";
import {
  AvatarBadgeDemo,
  AvatarBadgeIconDemo,
  AvatarDemo,
  AvatarDropdownDemo,
  AvatarFallbackDemo,
  AvatarGroupIconDemo,
  AvatarGroupCountDemo,
  AvatarGroupDemo,
  AvatarSizeDemo,
} from "~/components/demos/avatar";
import {
  BadgeDemo,
  BadgeIconDemo,
  BadgeLinkDemo,
  BadgeSizeDemo,
  BadgeStatusDemo,
  BadgeVariantsDemo,
} from "~/components/demos/badge";
import {
  ButtonDemo,
  ButtonIconDemo,
  ButtonIconOnlyDemo,
  ButtonLinkDemo,
  ButtonPillDemo,
  ButtonSizesDemo,
  ButtonBusyDemo,
  ButtonDisabledDemo,
  ButtonVariantsDemo,
} from "~/components/demos/button";
import {
  ButtonGroupDemo,
  ButtonGroupDropdownDemo,
  ButtonGroupInputDemo,
  ButtonGroupInputGroupDemo,
  ButtonGroupNestedDemo,
  ButtonGroupOrientationDemo,
  ButtonGroupPopoverDemo,
  ButtonGroupSelectDemo,
  ButtonGroupSeparatorDemo,
  ButtonGroupSizeDemo,
  ButtonGroupSplitDemo,
  ButtonGroupTextDemo,
} from "~/components/demos/button-group";
import { CardDemo, CardSizeDemo, CardWellDemo } from "~/components/demos/card";
import {
  CheckboxControlledDemo,
  CheckboxDemo,
  CheckboxDisabledDemo,
  CheckboxIndeterminateDemo,
  CheckboxInvalidDemo,
  CheckboxSizeDemo,
  CheckboxTableDemo,
} from "~/components/demos/checkbox";
import { CollapsibleDemo } from "~/components/demos/collapsible";
import { ColorRolesDemo, ColorScalesDemo } from "~/components/demos/color";
import { CommandDemo, CommandDialogDemo } from "~/components/demos/command";
import {
  DialogControlledDemo,
  DialogDemo,
  DialogScrollableDemo,
  DialogSizeDemo,
} from "~/components/demos/dialog";
import {
  DropdownMenuCheckboxesDemo,
  DropdownMenuDangerDemo,
  DropdownMenuDemo,
  DropdownMenuIconsDemo,
  DropdownMenuRadioGroupDemo,
  DropdownMenuSizesDemo,
  DropdownMenuSubmenuDemo,
} from "~/components/demos/dropdown-menu";
import {
  EmptyAvatarDemo,
  EmptyCardDemo,
  EmptyDemo,
} from "~/components/demos/empty";
import {
  FieldCardDemo,
  FieldDemo,
  FieldDisabledDemo,
  FieldFormDemo,
  FieldGroupDemo,
  FieldInputDemo,
  FieldRadioDemo,
  FieldSelectDemo,
  FieldSliderDemo,
  FieldSwitchDemo,
  FieldTextareaDemo,
  FieldErrorDemo,
  FieldSetDemo,
} from "~/components/demos/field";
import {
  InputBadgeDemo,
  InputButtonGroupDemo,
  InputFormDemo,
  InputDemo,
  InputDisabledDemo,
  InputFieldDemo,
  InputFieldGroupDemo,
  InputFileDemo,
  InputGridDemo,
  InputInlineDemo,
  InputInputGroupDemo,
  InputInvalidDemo,
  InputRequiredDemo,
  InputSizeDemo,
} from "~/components/demos/input";
import {
  InputGroupBlockEndDemo,
  InputGroupBlockStartDemo,
  InputGroupButtonDemo,
  InputGroupCustomDemo,
  InputGroupDemo,
  InputGroupIconDemo,
  InputGroupInlineEndDemo,
  InputGroupInlineStartDemo,
  InputGroupDropdownDemo,
  InputGroupKbdDemo,
  InputGroupSizeDemo,
  InputGroupSpinnerDemo,
  InputGroupTextareaDemo,
  InputGroupTextDemo,
} from "~/components/demos/input-group";
import {
  ItemAvatarDemo,
  ItemDemo,
  ItemGroupDemo,
  ItemIconDemo,
  ItemLinkDemo,
  ItemSizeDemo,
  ItemVariantDemo,
} from "~/components/demos/item";
import {
  KbdButtonDemo,
  KbdDemo,
  KbdGroupDemo,
  KbdTooltipDemo,
} from "~/components/demos/kbd";
import { LabelDemo } from "~/components/demos/label";
import { LayoutRadiiDemo, LayoutSizesDemo } from "~/components/demos/layout";
import { MotionEasingDemo } from "~/components/demos/motion";
import {
  PopoverAlignDemo,
  PopoverDemo,
  PopoverFormDemo,
} from "~/components/demos/popover";
import { PreviewCardDemo } from "~/components/demos/preview-card";
import {
  MeterDemo,
  ProgressDemo,
  ProgressLabelDemo,
} from "~/components/demos/progress";
import {
  RadioGroupCardDemo,
  RadioGroupDemo,
  RadioGroupDescriptionDemo,
  RadioGroupDisabledDemo,
  RadioGroupFieldsetDemo,
  RadioGroupInvalidDemo,
  RadioGroupSizeDemo,
} from "~/components/demos/radio-group";
import {
  ScrollAreaDemo,
  ScrollAreaHorizontalDemo,
} from "~/components/demos/scroll-area";
import {
  SelectAlignItemDemo,
  SelectDemo,
  SelectDisabledDemo,
  SelectGroupsDemo,
  SelectInvalidDemo,
  SelectScrollableDemo,
  SelectSizesDemo,
} from "~/components/demos/select";
import {
  SeparatorDemo,
  SeparatorListDemo,
  SeparatorMenuDemo,
  SeparatorVerticalDemo,
} from "~/components/demos/separator";
import { SheetDemo, SheetSideDemo } from "~/components/demos/sheet";
import { SkeletonCardDemo, SkeletonDemo } from "~/components/demos/skeleton";
import {
  SliderDemo,
  SliderDisabledDemo,
  SliderInputDemo,
  SliderMultipleDemo,
  SliderRangeDemo,
  SliderReferencesDemo,
  SliderStepsDemo,
  SliderTooltipDemo,
  SliderVerticalDemo,
} from "~/components/demos/slider";
import { SpinnerDemo } from "~/components/demos/spinner";
import {
  CopyButtonDemo,
  CopyButtonVariantDemo,
  SwapIconDemo,
  SwapTextDemo,
} from "~/components/demos/swap";
import {
  SwitchCardDemo,
  SwitchDemo,
  SwitchDescriptionDemo,
  SwitchDisabledDemo,
  SwitchInvalidDemo,
  SwitchSizesDemo,
} from "~/components/demos/switch";
import {
  TableActionsDemo,
  TableDemo,
  TableFooterDemo,
  TableSizeDemo,
} from "~/components/demos/table";
import {
  TabsDemo,
  TabsDisabledDemo,
  TabsLineDemo,
  TabsSizeDemo,
  TabsVerticalDemo,
} from "~/components/demos/tabs";
import {
  TextareaButtonDemo,
  TextareaDemo,
  TextareaDisabledDemo,
  TextareaFieldDemo,
  TextareaInvalidDemo,
  TextareaSizeDemo,
} from "~/components/demos/textarea";
import { ThemeBuilderDemo } from "~/components/demos/theme";
import {
  ToastActionDemo,
  ToastDemo,
  ToastDismissDemo,
  ToastPromiseDemo,
  ToastTypesDemo,
} from "~/components/demos/toast";
import {
  ToggleDemo,
  ToggleDisabledDemo,
  ToggleGroupDemo,
  ToggleGroupSizeDemo,
  ToggleGroupSpacingDemo,
  ToggleOutlineDemo,
  ToggleSizeDemo,
} from "~/components/demos/toggle";
import {
  TooltipDemo,
  TooltipDisabledDemo,
  TooltipKbdDemo,
  TooltipSideDemo,
} from "~/components/demos/tooltip";
import { TypographyDemo } from "~/components/demos/typography";

const demos = {
  alert: AlertDemo,
  "alert-action": AlertActionDemo,
  "alert-status": AlertStatusDemo,
  "alert-dialog": AlertDialogDemo,
  "alert-dialog-danger": AlertDialogDangerDemo,
  "alert-dialog-size": AlertDialogSizeDemo,
  avatar: AvatarDemo,
  "avatar-badge": AvatarBadgeDemo,
  "avatar-badge-icon": AvatarBadgeIconDemo,
  "avatar-dropdown": AvatarDropdownDemo,
  "avatar-fallback": AvatarFallbackDemo,
  "avatar-group": AvatarGroupDemo,
  "avatar-group-count": AvatarGroupCountDemo,
  "avatar-group-icon": AvatarGroupIconDemo,
  "avatar-size": AvatarSizeDemo,
  badge: BadgeDemo,
  "badge-icon": BadgeIconDemo,
  "badge-link": BadgeLinkDemo,
  "badge-size": BadgeSizeDemo,
  "badge-status": BadgeStatusDemo,
  "badge-variants": BadgeVariantsDemo,
  button: ButtonDemo,
  "button-icon": ButtonIconDemo,
  "button-icon-only": ButtonIconOnlyDemo,
  "button-link": ButtonLinkDemo,
  "button-pill": ButtonPillDemo,
  "button-sizes": ButtonSizesDemo,
  "button-busy": ButtonBusyDemo,
  "button-disabled": ButtonDisabledDemo,
  "button-variants": ButtonVariantsDemo,
  card: CardDemo,
  "card-size": CardSizeDemo,
  "card-well": CardWellDemo,
  "button-group": ButtonGroupDemo,
  "button-group-dropdown": ButtonGroupDropdownDemo,
  "button-group-input": ButtonGroupInputDemo,
  "button-group-input-group": ButtonGroupInputGroupDemo,
  "button-group-nested": ButtonGroupNestedDemo,
  "button-group-orientation": ButtonGroupOrientationDemo,
  "button-group-popover": ButtonGroupPopoverDemo,
  "button-group-select": ButtonGroupSelectDemo,
  "button-group-separator": ButtonGroupSeparatorDemo,
  "button-group-size": ButtonGroupSizeDemo,
  "button-group-split": ButtonGroupSplitDemo,
  "button-group-text": ButtonGroupTextDemo,
  checkbox: CheckboxDemo,
  "checkbox-controlled": CheckboxControlledDemo,
  "checkbox-disabled": CheckboxDisabledDemo,
  "checkbox-indeterminate": CheckboxIndeterminateDemo,
  "checkbox-invalid": CheckboxInvalidDemo,
  "checkbox-size": CheckboxSizeDemo,
  "checkbox-table": CheckboxTableDemo,
  "color-roles": ColorRolesDemo,
  "color-scales": ColorScalesDemo,
  collapsible: CollapsibleDemo,
  command: CommandDemo,
  "command-dialog": CommandDialogDemo,
  "copy-button": CopyButtonDemo,
  "copy-button-variant": CopyButtonVariantDemo,
  dialog: DialogDemo,
  "dialog-controlled": DialogControlledDemo,
  "dialog-scrollable": DialogScrollableDemo,
  "dialog-size": DialogSizeDemo,
  "dropdown-menu": DropdownMenuDemo,
  "dropdown-menu-checkboxes": DropdownMenuCheckboxesDemo,
  "dropdown-menu-danger": DropdownMenuDangerDemo,
  "dropdown-menu-icons": DropdownMenuIconsDemo,
  "dropdown-menu-radio-group": DropdownMenuRadioGroupDemo,
  "dropdown-menu-sizes": DropdownMenuSizesDemo,
  "dropdown-menu-submenu": DropdownMenuSubmenuDemo,
  empty: EmptyDemo,
  "empty-avatar": EmptyAvatarDemo,
  "empty-card": EmptyCardDemo,
  field: FieldDemo,
  "field-card": FieldCardDemo,
  "field-disabled": FieldDisabledDemo,
  "field-form": FieldFormDemo,
  "field-group": FieldGroupDemo,
  "field-input": FieldInputDemo,
  "field-radio": FieldRadioDemo,
  "field-select": FieldSelectDemo,
  "field-slider": FieldSliderDemo,
  "field-switch": FieldSwitchDemo,
  "field-textarea": FieldTextareaDemo,
  "field-error": FieldErrorDemo,
  "field-set": FieldSetDemo,
  input: InputDemo,
  "input-badge": InputBadgeDemo,
  "input-button-group": InputButtonGroupDemo,
  "input-form": InputFormDemo,
  "input-disabled": InputDisabledDemo,
  "input-field": InputFieldDemo,
  "input-field-group": InputFieldGroupDemo,
  "input-file": InputFileDemo,
  "input-grid": InputGridDemo,
  "input-group": InputGroupDemo,
  "input-group-block-end": InputGroupBlockEndDemo,
  "input-group-block-start": InputGroupBlockStartDemo,
  "input-group-button": InputGroupButtonDemo,
  "input-group-custom": InputGroupCustomDemo,
  "input-group-icon": InputGroupIconDemo,
  "input-group-inline-end": InputGroupInlineEndDemo,
  "input-group-inline-start": InputGroupInlineStartDemo,
  "input-group-dropdown": InputGroupDropdownDemo,
  "input-group-kbd": InputGroupKbdDemo,
  "input-group-size": InputGroupSizeDemo,
  "input-group-spinner": InputGroupSpinnerDemo,
  "input-group-text": InputGroupTextDemo,
  "input-group-textarea": InputGroupTextareaDemo,
  "input-inline": InputInlineDemo,
  "input-input-group": InputInputGroupDemo,
  "input-invalid": InputInvalidDemo,
  "input-required": InputRequiredDemo,
  "input-size": InputSizeDemo,
  item: ItemDemo,
  "item-avatar": ItemAvatarDemo,
  "item-group": ItemGroupDemo,
  "item-icon": ItemIconDemo,
  "item-link": ItemLinkDemo,
  "item-size": ItemSizeDemo,
  "item-variant": ItemVariantDemo,
  kbd: KbdDemo,
  "kbd-button": KbdButtonDemo,
  "kbd-group": KbdGroupDemo,
  "kbd-tooltip": KbdTooltipDemo,
  label: LabelDemo,
  "layout-radii": LayoutRadiiDemo,
  "layout-sizes": LayoutSizesDemo,
  "motion-easing": MotionEasingDemo,
  separator: SeparatorDemo,
  meter: MeterDemo,
  popover: PopoverDemo,
  "popover-align": PopoverAlignDemo,
  "popover-form": PopoverFormDemo,
  "preview-card": PreviewCardDemo,
  progress: ProgressDemo,
  "progress-label": ProgressLabelDemo,
  "radio-group": RadioGroupDemo,
  "radio-group-card": RadioGroupCardDemo,
  "radio-group-description": RadioGroupDescriptionDemo,
  "radio-group-disabled": RadioGroupDisabledDemo,
  "radio-group-fieldset": RadioGroupFieldsetDemo,
  "radio-group-invalid": RadioGroupInvalidDemo,
  "radio-group-size": RadioGroupSizeDemo,
  "scroll-area": ScrollAreaDemo,
  "scroll-area-horizontal": ScrollAreaHorizontalDemo,
  select: SelectDemo,
  "select-align-item": SelectAlignItemDemo,
  "select-disabled": SelectDisabledDemo,
  "select-groups": SelectGroupsDemo,
  "select-invalid": SelectInvalidDemo,
  "select-scrollable": SelectScrollableDemo,
  "select-sizes": SelectSizesDemo,
  "separator-list": SeparatorListDemo,
  "separator-menu": SeparatorMenuDemo,
  "separator-vertical": SeparatorVerticalDemo,
  sheet: SheetDemo,
  "sheet-side": SheetSideDemo,
  skeleton: SkeletonDemo,
  "skeleton-card": SkeletonCardDemo,
  slider: SliderDemo,
  "slider-disabled": SliderDisabledDemo,
  "slider-input": SliderInputDemo,
  "slider-multiple": SliderMultipleDemo,
  "slider-range": SliderRangeDemo,
  "slider-references": SliderReferencesDemo,
  "slider-steps": SliderStepsDemo,
  "slider-tooltip": SliderTooltipDemo,
  "slider-vertical": SliderVerticalDemo,
  spinner: SpinnerDemo,
  toast: ToastDemo,
  "toast-action": ToastActionDemo,
  "toast-dismiss": ToastDismissDemo,
  "toast-promise": ToastPromiseDemo,
  "toast-types": ToastTypesDemo,
  "swap-icon": SwapIconDemo,
  "swap-text": SwapTextDemo,
  switch: SwitchDemo,
  "switch-card": SwitchCardDemo,
  "switch-description": SwitchDescriptionDemo,
  "switch-disabled": SwitchDisabledDemo,
  "switch-invalid": SwitchInvalidDemo,
  "switch-sizes": SwitchSizesDemo,
  table: TableDemo,
  "table-actions": TableActionsDemo,
  "table-footer": TableFooterDemo,
  "table-size": TableSizeDemo,
  tabs: TabsDemo,
  "tabs-disabled": TabsDisabledDemo,
  "tabs-line": TabsLineDemo,
  "tabs-size": TabsSizeDemo,
  "tabs-vertical": TabsVerticalDemo,
  textarea: TextareaDemo,
  "textarea-button": TextareaButtonDemo,
  "textarea-disabled": TextareaDisabledDemo,
  "textarea-field": TextareaFieldDemo,
  "textarea-invalid": TextareaInvalidDemo,
  "textarea-size": TextareaSizeDemo,
  "theme-builder": ThemeBuilderDemo,
  toggle: ToggleDemo,
  "toggle-disabled": ToggleDisabledDemo,
  "toggle-group": ToggleGroupDemo,
  "toggle-group-size": ToggleGroupSizeDemo,
  "toggle-group-spacing": ToggleGroupSpacingDemo,
  "toggle-outline": ToggleOutlineDemo,
  "toggle-size": ToggleSizeDemo,
  tooltip: TooltipDemo,
  "tooltip-disabled": TooltipDisabledDemo,
  "tooltip-kbd": TooltipKbdDemo,
  "tooltip-side": TooltipSideDemo,
  typography: TypographyDemo,
} satisfies Record<string, ComponentType>;

function isDemo(name: string): name is keyof typeof demos {
  return Object.hasOwn(demos, name);
}

export { demos, isDemo };
